-- generated by movies_lib.documents_to_sql — อย่าแก้มือ
BEGIN;
DELETE FROM movies WHERE movie_id IN ('573a1390f29313caabcd42e8', '573a1390f29313caabcd446f');   -- ตารางลูกหายตามด้วย ON DELETE CASCADE

INSERT INTO movies (movie_id, title, type, year, rated, runtime_min, released, plot, fullplot, poster_url, num_mflix_comments, lastupdated, awards_wins, awards_nominations, awards_text, imdb_id, imdb_rating, imdb_votes, tomatoes_viewer_rating, tomatoes_viewer_reviews, tomatoes_viewer_meter, tomatoes_critic_rating, tomatoes_critic_reviews, tomatoes_critic_meter, tomatoes_fresh, tomatoes_rotten, tomatoes_lastupdated) VALUES
    ('573a1390f29313caabcd42e8', 'The Great Train Robbery', 'movie', 1903, 'TV-G', 11, '1903-12-01', 'A group of bandits stage a brazen train hold-up, only to find a determined posse hot on their heels.', 'Among the earliest existing films in American cinema - notable as the first film that presented a narrative story to tell - it depicts a group of cowboy outlaws who hold up a train and rob the passengers. They are then pursued by a Sheriff''s posse. Several scenes have color included - all hand tinted.', 'https://m.media-amazon.com/images/M/MV5BMTU3NjE5NzYtYTYyNS00MDVmLWIwYjgtMmYwYWIxZDYyNzU2XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_SY1000_SX677_AL_.jpg', 0, '2015-08-13 00:27:59.177000', 1, 0, '1 win.', 439, 7.4, 9847, 3.7, 2559, 75, 7.6, 6, 100, 6, 0, '2015-08-08 19:16:10+00:00'),
    ('573a1390f29313caabcd446f', 'A Corner in Wheat', 'movie', 1909, 'G', 14, '1909-12-13', 'A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain''s producers into charity lines and further into poverty. The film...', 'A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain''s producers into charity lines and further into poverty. The film continues to contrast the ironic differences between the lives of those who work to grow the wheat and the life of the man who dabbles in its sale for profit.', NULL, 1, '2015-08-13 00:46:30.660000', 1, 0, '1 win.', 832, 6.6, 1375, 3.6, 109, 73, NULL, NULL, NULL, NULL, NULL, '2015-05-11 18:36:53+00:00');

INSERT INTO movie_genres (movie_id, genre) VALUES
    ('573a1390f29313caabcd42e8', 'Short'),
    ('573a1390f29313caabcd42e8', 'Western'),
    ('573a1390f29313caabcd446f', 'Short'),
    ('573a1390f29313caabcd446f', 'Drama');

INSERT INTO movie_cast (movie_id, position, actor_name) VALUES
    ('573a1390f29313caabcd42e8', 1, 'A.C. Abadie'),
    ('573a1390f29313caabcd42e8', 2, 'Gilbert M. ''Broncho Billy'' Anderson'),
    ('573a1390f29313caabcd42e8', 3, 'George Barnes'),
    ('573a1390f29313caabcd42e8', 4, 'Justus D. Barnes'),
    ('573a1390f29313caabcd446f', 1, 'Frank Powell'),
    ('573a1390f29313caabcd446f', 2, 'Grace Henderson'),
    ('573a1390f29313caabcd446f', 3, 'James Kirkwood'),
    ('573a1390f29313caabcd446f', 4, 'Linda Arvidson');

INSERT INTO movie_directors (movie_id, position, director_name) VALUES
    ('573a1390f29313caabcd42e8', 1, 'Edwin S. Porter'),
    ('573a1390f29313caabcd446f', 1, 'D.W. Griffith');

INSERT INTO movie_languages (movie_id, language) VALUES
    ('573a1390f29313caabcd42e8', 'English'),
    ('573a1390f29313caabcd446f', 'English');

INSERT INTO movie_countries (movie_id, country) VALUES
    ('573a1390f29313caabcd42e8', 'USA'),
    ('573a1390f29313caabcd446f', 'USA');

COMMIT;